### ISSUE TITLE
Add wording to lower fear of running this on remote nodes

### ISSUE THREAD

**Issue by brontidebrontide** [kn6plv/waterfall#2]
Due to the note "Running the waterfall will disconnect your radio from the mesh.", I was afraid to run this on any remote nodes but have found (fingers crossed!) that I was able to get back to the node(s).  My fear was that I would take the node offline and it would never come back.  Evidently, clicking "Back" on my browser brought it back to the usual node page.
So, the suggestion is to add some kind of wording to ease those fears.

**Comment by aanon4** [comment]
This has been observed by a number of people now, so I've removed the warning from the main page.
